# Generated by Django 4.1.9 on 2023-07-04 06:06

from django.db import migrations, models
import djongo.models.fields
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_hash', models.CharField(max_length=100)),
                ('current_hash', models.CharField(max_length=100)),
                ('transactions', djongo.models.fields.ArrayField(model_container=main.models.Transaction)),
            ],
            options={
                'db_table': 'Blockchain',
            },
        ),
        migrations.CreateModel(
            name='LandList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_code', models.IntegerField()),
                ('note', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LandList',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('plot_code', models.IntegerField()),
                ('sender_username', models.CharField(max_length=100)),
                ('receiver_username', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
    ]
